// Demo data for deardiary.
// Each session is a phone call with the agent. Transcript turns alternate:
// 'a' = agent (rendered as small italic prompts), 'u' = user (main prose).

export const SESSIONS = [
  {
    id: 'today',
    date: '2026-05-17',
    weekday: 'Sunday',
    time: 'today',
    duration: 'open',
    mood: 'open',
    title: 'today',
    isToday: true,
    transcript: [
      { who: 'a', text: 'Good morning. What’s the temperature in your chest, right now?' },
      { who: 'u', text: "Quiet. A little wide-open. The kind of Sunday where I'm trying to decide whether to call mom or just sit on the back step for an hour and not call anyone." },
      { who: 'a', text: 'what would tell you which to do?' },
    ],
  },
  {
    id: 'may14-late',
    date: '2026-05-14',
    weekday: 'Thursday',
    time: '11:47 PM',
    duration: '8 min',
    mood: 'tender',
    title: 'About not replying yet',
    transcript: [
      { who: 'a', text: 'Hi. How are you, this late?' },
      { who: 'u', text: "Worn down, honestly. I've been holding Sam's message in my hand for about four hours now and I haven't replied. I read it twice in the kitchen, twice on the couch, and once in the bathroom mirror like that would help." },
      { who: 'a', text: 'what does the message ask of you?' },
      { who: 'u', text: "It doesn't ask anything. That's the part. It's just — kind. And I don't know what to do with kind right now. I think I want to be a little angry for another day before I let it land." },
      { who: 'a', text: 'is a day enough?' },
      { who: 'u', text: "Probably not. But I want to be the one who decides when. Even if no one is watching me decide." },
    ],
  },
  {
    id: 'may13-am',
    date: '2026-05-13',
    weekday: 'Wednesday',
    time: '7:08 AM',
    duration: '22 min',
    mood: 'anxious → settled',
    title: 'The Tuesday talk',
    transcript: [
      { who: 'a', text: 'Good morning. You said yesterday you wanted to think out loud about Tuesday.' },
      { who: 'u', text: "Yeah. The deck is fine. The deck has been fine for a week. The problem is I keep writing a speech for the version of me that's already given this talk, and the version of me who's actually going to give it is going to be holding a clicker and wishing I'd written a different one." },
      { who: 'a', text: 'what would that other speech say?' },
      { who: 'u', text: "That I'm not sure about the second half. That the numbers tell one story and the room is going to want another and I'm tired of pretending the gap doesn't exist. I want to just name it on slide one and let the rest be honest." },
      { who: 'a', text: 'what stops you?' },
      { who: 'u', text: "Habit. The shape a talk like this is supposed to take. Eli would say do it. Mira would say do it. I would say do it if it weren't me up there." },
      { who: 'a', text: 'so do it.' },
      { who: 'u', text: "Yeah. Okay. I'll rewrite the open this morning and stop pretending I haven't already decided." },
    ],
  },
  {
    id: 'may11-pm',
    date: '2026-05-11',
    weekday: 'Monday',
    time: '9:30 PM',
    duration: '6 min',
    mood: 'grateful',
    title: 'Dinner at Mira’s',
    transcript: [
      { who: 'a', text: 'You sound lighter tonight.' },
      { who: 'u', text: "Mira made that lemon thing again and asked me what the book is actually about, not what I tell people it's about. I haven't been asked the real version in a while. I forgot I had an answer." },
      { who: 'a', text: 'what was the answer?' },
      { who: 'u', text: "Something about staying in a room that wants you to leave. I'll write it down properly tomorrow. Right now I just want to remember the kitchen." },
    ],
  },
  {
    id: 'may10-am',
    date: '2026-05-10',
    weekday: 'Sunday',
    time: '8:15 AM',
    duration: '11 min',
    mood: 'soft',
    title: 'Garden, dad, Saturday',
    transcript: [
      { who: 'a', text: 'Morning. What does today have in it?' },
      { who: 'u', text: "The garden, mostly. The mint has gone completely feral and I think I have to be okay with that. Also dad's seventy on Saturday and I still haven't written the toast." },
      { who: 'a', text: 'what would you say if you weren’t writing a toast?' },
      { who: 'u', text: "That he taught me how to leave things alone when they were almost ready. Which is — yeah. That's the toast, isn't it." },
    ],
  },
  {
    id: 'may08-pm',
    date: '2026-05-08',
    weekday: 'Friday',
    time: '10:51 PM',
    duration: '4 min',
    mood: 'tired',
    title: 'Just a check-in',
    transcript: [
      { who: 'a', text: 'Short one tonight?' },
      { who: 'u', text: "Yeah. I'm okay. I just wanted to hear myself say I'm okay out loud before I went to bed. That's it." },
    ],
  },
  {
    id: 'may07-am',
    date: '2026-05-07',
    weekday: 'Thursday',
    time: '6:55 AM',
    duration: '17 min',
    mood: 'restless',
    title: 'The dream with the train',
    transcript: [
      { who: 'a', text: 'You wrote yesterday that this one keeps coming back.' },
      { who: 'u', text: "Sam was on the train and I couldn't get the doors open. I kept reaching for the lever and my hand wouldn't close around it. I keep thinking it means something but maybe it just means I'm tired of trains." },
      { who: 'a', text: 'what’s the part you return to?' },
      { who: 'u', text: "The doors. That I knew where the lever was and couldn't get there in time. Everything else in the dream I can let go of. Not that." },
    ],
  },
];

// Life OS cards — the agent assembles these mini-apps from what comes up in calls.
// kind drives the visual; content is per-card.
export const LIFEOS_CARDS = [
  {
    id: 'mood',
    kind: 'mood',
    title: 'mood, last 14 days',
    sub: 'auto · from your calls',
    size: 'wide',
    data: [3, 2, 4, 4, 3, 2, 1, 2, 3, 4, 3, 2, 2, 3],
  },
  {
    id: 'sam',
    kind: 'person',
    title: 'Sam',
    sub: 'mentioned 6 times this month',
    size: 'tall',
    notes: [
      'May 14 — read their message four times, didn’t reply.',
      'May 7 — the train dream again. The doors.',
      'Apr 29 — the voicemail you didn’t leave.',
      'Apr 22 — “I want to be the one who decides when.”',
    ],
    sentiment: 'unresolved',
  },
  {
    id: 'talk',
    kind: 'project',
    title: 'Tuesday talk · 10:30 AM',
    sub: 'in 5 days',
    size: 'reg',
    steps: [
      { done: true, text: 'rewrite the open, honestly' },
      { done: true, text: 'cut slide 11' },
      { done: false, text: 'practice the second half once' },
      { done: false, text: 'water before, not during' },
    ],
  },
  {
    id: 'dad',
    kind: 'countdown',
    title: 'Dad turns 70',
    sub: 'Saturday',
    size: 'reg',
    days: 2,
    toast: '“He taught me how to leave things alone when they were almost ready.”',
  },
  {
    id: 'returning',
    kind: 'themes',
    title: 'what you keep returning to',
    sub: 'last 30 days',
    size: 'tall',
    items: [
      { word: 'doors', count: 7 },
      { word: 'the kitchen', count: 5 },
      { word: 'deciding when', count: 4 },
      { word: 'the book', count: 4 },
      { word: 'being honest on slide one', count: 3 },
      { word: 'the mint', count: 2 },
    ],
  },
  {
    id: 'sleep',
    kind: 'sleep',
    title: 'sleep, this week',
    sub: 'from when you call',
    size: 'reg',
    nights: [
      { h: 6.2, late: true },
      { h: 7.0, late: false },
      { h: 5.5, late: true },
      { h: 7.5, late: false },
      { h: 6.0, late: true },
      { h: 8.0, late: false },
      { h: 5.0, late: true },
    ],
  },
  {
    id: 'unsent',
    kind: 'letters',
    title: 'letters you didn’t send',
    sub: '3 drafts, in your voice',
    size: 'reg',
    drafts: [
      { to: 'Sam', line: 'I wanted to be a little angry for another day.' },
      { to: 'Mira', line: 'The real version of the book is this — ' },
      { to: 'me, six months ago', line: 'You were right about leaving.' },
    ],
  },
  {
    id: 'reread',
    kind: 'list',
    title: 'read again',
    sub: 'things you brought up',
    size: 'reg',
    items: [
      'the Berger essay about looking',
      'the second half of Mary Oliver',
      'your own July notebook',
    ],
  },
];
